server:
  port: 8081

spring:
  application:
    name: task-tracker-email-sender

kafka:
    bootstrap-servers: kafka:9092

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus

  endpoint:
    prometheus:
      access: unrestricted

  metrics:
    tags:
      application: ${spring.application.name}

unisender:
  baseUrl: https://api.unisender.com/ru/api
  apiKey: ${unisender.apiKey}
