server:
  port: 8081

spring:
  application:
    name: task-tracker-email-sender

kafka:
    bootstrap-servers: kafka:9092

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus

  endpoint:
    prometheus:
      access: unrestricted

  metrics:
    tags:
      application: ${spring.application.name}

unisender:
  baseUrl: https://api.unisender.com/ru/api
  apiKey: ${unisender.apiKey}

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p --- [%15.15t] %-40.40logger{39} : %m%n%kvp"
