services:
  task-tracker-backend:
    build:
      context: ./task-tracker-backend
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      APP_FRONTEND_URL: ${APP_FRONTEND_URL}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/backend_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      APP_JWT_SECRET: ${JWT_SECRET}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092


  task-tracker-email-sender:
    build:
      context: ./task-tracker-email-sender
      dockerfile: Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      UNISENDER_API_KEY: ${UNISENDER_API_KEY}
      APP_URL: ${APP_URL}


  task-tracker-summarization-service:
    build:
      context: ./task-tracker-summarization-service
      dockerfile: Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}


  task-tracker-scheduler:
    build:
      context: ./task-tracker-scheduler
      dockerfile: Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    depends_on:
      - task-tracker-backend
      - task-tracker-email-sender
      - task-tracker-summarization-service
      - task-tracker-scheduler

    ports:
      - "5173:80"


  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5440:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5


  kafka:
    image: apache/kafka:3.9.0

    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - kafka_data:/var/lib/kafka/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092"
        ]
      interval: 10s
      timeout: 10s
      retries: 5


  # =========================
  # Monitoring
  # =========================

  prometheus:
    image: prom/prometheus:v3.0.1

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

    restart: unless-stopped


  grafana:
    image: grafana/grafana-oss:11.4.0

    ports:
      - "3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards

    depends_on:
      - prometheus
      - loki

    restart:
      unless-stopped


  # =========================
  # Logs
  # =========================

  loki:
    image: grafana/loki:3.3.2

    ports:
      - "3100:3100"

    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki

    command:
      - "-config.file=/etc/loki/local-config.yaml"

    restart:
      unless-stopped

volumes:
  postgres_data:
  kafka_data:

  prometheus_data:
  grafana_data:

  loki_data: