server:
  port: 8082

spring:
  application:
    name: task-tracker-summarization-server

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: report-requests
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: task_scheduler.task_tracker_summarization_server.dto
        spring.json.value.default.type: task_scheduler.task_tracker_summarization_server.dto.ReportRequest

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false