server:
  port: 8083

spring:
  application:
    name: task-tracker-scheduler

internal:
  api-key: ${INTERNAL_API_KEY}

backend:
  url: http://task-tracker-backend:8080

kafka:
  bootstrap-servers: kafka:9092

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus

  endpoint:
    prometheus:
      access: unrestricted

  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p --- [%15.15t] %-40.40logger{39} : %m%n%kvp"