server:
  port: 8083

spring:
  application:
    name: task-tracker-scheduler
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

internal:
  api-key: ${INTERNAL_API_KEY}

backend:
  url: http://task-tracker-backend:8080